name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # Coloque a versão do Go que você usa

    - name: Instalar dependências
      run: go mod tidy

    - name: Rodar testes
      run: go test ./...

